const abi = [
  {
    type: 'constructor',
    inputs: [
      { name: '_xid', type: 'address', internalType: 'address' },
      { name: '_vault', type: 'address', internalType: 'address' },
      { name: '_feeReceiver', type: 'address', internalType: 'address' },
    ],
    stateMutability: 'nonpayable',
  },
  { type: 'receive', stateMutability: 'payable' },
  {
    type: 'function',
    name: 'batchTransferEth',
    inputs: [
      { name: 'toUsernames', type: 'string[]', internalType: 'string[]' },
      { name: 'vaultAmounts', type: 'uint256[]', internalType: 'uint256[]' },
      { name: 'toAddresses', type: 'address[]', internalType: 'address[]' },
      { name: 'directAmounts', type: 'uint256[]', internalType: 'uint256[]' },
    ],
    outputs: [],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'batchTransferToken',
    inputs: [
      { name: 'toUsernames', type: 'string[]', internalType: 'string[]' },
      { name: 'vaultAmounts', type: 'uint256[]', internalType: 'uint256[]' },
      { name: 'toAddresses', type: 'address[]', internalType: 'address[]' },
      { name: 'directAmounts', type: 'uint256[]', internalType: 'uint256[]' },
      { name: 'token', type: 'address', internalType: 'address' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'feeRate',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'feeReceiver',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'owner',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'renounceOwnership',
    inputs: [],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'setFeeRate',
    inputs: [{ name: '_newRate', type: 'uint256', internalType: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'setFeeReceiver',
    inputs: [
      { name: '_newReceiver', type: 'address', internalType: 'address' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'transferEth',
    inputs: [{ name: 'toUsername', type: 'string', internalType: 'string' }],
    outputs: [],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'transferOwnership',
    inputs: [{ name: 'newOwner', type: 'address', internalType: 'address' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'transferToken',
    inputs: [
      { name: 'toUsername', type: 'string', internalType: 'string' },
      { name: 'amount', type: 'uint256', internalType: 'uint256' },
      { name: 'token', type: 'address', internalType: 'address' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'vault',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'contract IXVault' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'xid',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'contract IXID' }],
    stateMutability: 'view',
  },
  {
    type: 'event',
    name: 'BatchEthTransferred',
    inputs: [
      { name: 'from', type: 'address', indexed: true, internalType: 'address' },
      {
        name: 'toUsernames',
        type: 'string[]',
        indexed: false,
        internalType: 'string[]',
      },
      {
        name: 'toAddresses',
        type: 'address[]',
        indexed: false,
        internalType: 'address[]',
      },
      {
        name: 'totalVaultAmount',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'totalDirectAmount',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'totalFee',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'BatchTokenTransferred',
    inputs: [
      { name: 'from', type: 'address', indexed: true, internalType: 'address' },
      {
        name: 'token',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      {
        name: 'toUsernames',
        type: 'string[]',
        indexed: false,
        internalType: 'string[]',
      },
      {
        name: 'toAddresses',
        type: 'address[]',
        indexed: false,
        internalType: 'address[]',
      },
      {
        name: 'totalVaultAmount',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'totalDirectAmount',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'totalFee',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'EthTransferred',
    inputs: [
      { name: 'from', type: 'address', indexed: true, internalType: 'address' },
      {
        name: 'toUsername',
        type: 'string',
        indexed: true,
        internalType: 'string',
      },
      {
        name: 'amount',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      { name: 'fee', type: 'uint256', indexed: false, internalType: 'uint256' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'FeeRateUpdated',
    inputs: [
      {
        name: 'newRate',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'FeeReceiverUpdated',
    inputs: [
      {
        name: 'newReceiver',
        type: 'address',
        indexed: false,
        internalType: 'address',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'OwnershipTransferred',
    inputs: [
      {
        name: 'previousOwner',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      {
        name: 'newOwner',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'TokenTransferred',
    inputs: [
      { name: 'from', type: 'address', indexed: true, internalType: 'address' },
      {
        name: 'toUsername',
        type: 'string',
        indexed: true,
        internalType: 'string',
      },
      {
        name: 'token',
        type: 'address',
        indexed: false,
        internalType: 'address',
      },
      {
        name: 'amount',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      { name: 'fee', type: 'uint256', indexed: false, internalType: 'uint256' },
    ],
    anonymous: false,
  },
  {
    type: 'error',
    name: 'OwnableInvalidOwner',
    inputs: [{ name: 'owner', type: 'address', internalType: 'address' }],
  },
  {
    type: 'error',
    name: 'OwnableUnauthorizedAccount',
    inputs: [{ name: 'account', type: 'address', internalType: 'address' }],
  },
  { type: 'error', name: 'ReentrancyGuardReentrantCall', inputs: [] },
];

export default abi;
