import React, { useState, useEffect } from 'react';
import { createPortal } from 'react-dom';
import { BadgeCheck, MessageCircle, Repeat, Heart, BarChart2, Send, Sparkles, RefreshCw, Undo, Trash2, X, Play, Calendar, ChevronLeft, ChevronRight } from 'lucide-react';
import { ImageWithSkeleton } from './ChatPanel';
import { AutoResizeTextarea } from '../AutoResizeTextarea';
import { NotificationToast } from '../NotificationToast';
import { tweetPoster } from '../../utils/tweetPoster';
import { useLanguage } from '../LanguageContext';
import { authService } from '../../services/authService';
import { EditableImage } from '../EditableImage';
import { useTheme } from '../ThemeContext';
import { TweetContentEditor } from './TweetContentEditor';

export interface RewrittenTweet {
    text: string;
    media: {
        type: 'photo' | 'video' | 'animated_gif';
        media_url: string;
        url: string;
        sizes?: any;
        video_url?: string;
        duration_ms?: number;
        aspect_ratio?: [number, number];
        thumbnail_url?: string; // Add if presented in other responses
        thumbnail?: string; // Add legacy thumbnail support
        isAIGenerated?: boolean; // Track if this image was generated by AI
    }[];
}

export interface RewrittenTimelineData {
    original_tweet_id: string;
    target_language: string;
    target_style: string | null;
    user: {
        username: string;
        display_name: string;
        avatar: string;
    };
    timeline: RewrittenTweet[];
    total_tweets: number;
}

export interface RewrittenTimelineProps {
    data: RewrittenTimelineData;
    userInfo?: {
        name: string;
        handle: string;
        avatar: string;
    } | null;
    onTimelineChange?: (newTimeline: RewrittenTweet[]) => void;
    draftId?: string;
    initialScheduledAt?: string | null;
}




const TimelineVideo: React.FC<{
    src: string;
    poster?: string;
    className?: string;
}> = ({ src, poster, className }) => {
    const [isPlaying, setIsPlaying] = useState(false);

    if (isPlaying) {
        return (
            <div className={`relative bg-black flex items-center justify-center overflow-hidden border border-[var(--border-color)] ${className}`}>
                <video
                    src={src}
                    controls
                    autoPlay
                    className="w-full h-full object-contain"
                />
            </div>
        );
    }

    return (
        <div
            className={`relative bg-black flex items-center justify-center cursor-pointer group overflow-hidden border border-[var(--border-color)] ${className}`}
            onClick={(e) => {
                e.stopPropagation();
                setIsPlaying(true);
            }}
        >
            {poster ? (
                <img
                    src={poster}
                    alt="Video thumbnail"
                    className="w-full h-full object-cover opacity-80 group-hover:opacity-100 transition-opacity"
                />
            ) : (
                <div className="w-full h-full bg-gray-900" />
            )}

            <div className="absolute inset-0 flex items-center justify-center bg-black/20 hover:bg-black/30 transition-all">
                <div className="w-16 h-16 rounded-full bg-black/60 backdrop-blur-sm flex items-center justify-center text-white hover:bg-black/70 hover:scale-105 transition-all border border-white/20">
                    <Play size={28} fill="currentColor" className="ml-1" />
                </div>
            </div>
        </div>
    );
};

export const RewrittenTimeline: React.FC<RewrittenTimelineProps> = ({ data, userInfo, onTimelineChange, draftId, initialScheduledAt }) => {
    const [isPosting, setIsPosting] = useState(false);
    const [progress, setProgress] = useState<{ current: number; total: number } | null>(null);

    const [isVerified, setIsVerified] = useState(false);
    const [previewImageUrl, setPreviewImageUrl] = useState<string | null>(null);
    const [isUploadingMedia, setIsUploadingMedia] = useState(false);
    const [draftOnly, setDraftOnly] = useState(true);

    // Toast state
    const [toastMsg, setToastMsg] = useState<string | null>(null);
    const showToast = (msg: string) => {
        setToastMsg(msg);
        setTimeout(() => setToastMsg(null), 2500);
    };

    // Schedule state
    const [showSchedulePicker, setShowSchedulePicker] = useState(false);
    const [scheduledDate, setScheduledDate] = useState<Date | null>(initialScheduledAt ? new Date(initialScheduledAt) : null);
    const [scheduleMonth, setScheduleMonth] = useState(new Date());
    const [scheduleHour, setScheduleHour] = useState(() => new Date().getHours().toString().padStart(2, '0'));
    const [scheduleMinute, setScheduleMinute] = useState(() => {
        const m = Math.ceil(new Date().getMinutes() / 5) * 5;
        return (m >= 60 ? 0 : m).toString().padStart(2, '0');
    });

    // Reset time to current when picker opens
    useEffect(() => {
        if (showSchedulePicker) {
            if (scheduledDate && scheduledDate.getTime() > Date.now()) {
                // Use existing scheduled time
                setScheduleHour(scheduledDate.getHours().toString().padStart(2, '0'));
                const m = Math.round(scheduledDate.getMinutes() / 5) * 5;
                setScheduleMinute((m >= 60 ? 0 : m).toString().padStart(2, '0'));
            } else {
                // Use current time
                const now = new Date();
                setScheduleHour(now.getHours().toString().padStart(2, '0'));
                const m = Math.ceil(now.getMinutes() / 5) * 5;
                setScheduleMinute((m >= 60 ? 0 : m).toString().padStart(2, '0'));
            }
        }
    }, [showSchedulePicker]);

    // Lower sidebar z-index when schedule picker is open so modal covers it
    useEffect(() => {
        if (showSchedulePicker) {
            const style = document.createElement('style');
            style.id = 'schedule-modal-sidebar-fix';
            style.textContent = `
                [data-testid="bnbot-sidebar"] {
                    z-index: 0 !important;
                }
                [data-testid="bnbot-sidebar"] * {
                    z-index: 0 !important;
                }
            `;
            const shadowContainer = document.getElementById('x-sidekick-container');
            const target = shadowContainer?.shadowRoot || document.head;
            target.appendChild(style);

            return () => {
                const existingStyle = (shadowContainer?.shadowRoot || document).getElementById('schedule-modal-sidebar-fix');
                existingStyle?.remove();
            };
        }
    }, [showSchedulePicker]);

    // Batch generation state


    // Get theme from context for button styling
    const { theme } = useTheme();
    const { t, language } = useLanguage();
    const isDark = theme === 'dark';

    // State to hold the current version of the timeline (allowing for image updates)
    const [timelineState, setTimelineState] = useState<RewrittenTweet[]>(data.timeline);
    // Track if user has made local edits (e.g., generated new images)
    const [hasLocalEdits, setHasLocalEdits] = useState(false);
    // Track the original tweet ID to detect when data truly changes
    const [originalTweetId, setOriginalTweetId] = useState(data.original_tweet_id);

    // Sync with props ONLY if data represents a completely different timeline
    useEffect(() => {
        if (data.original_tweet_id !== originalTweetId) {
            // Different tweet, reset everything
            setTimelineState(data.timeline);
            setHasLocalEdits(false);
            setOriginalTweetId(data.original_tweet_id);
        }
    }, [data.original_tweet_id, data.timeline, originalTweetId]);

    // Notify parent of changes
    useEffect(() => {
        if (hasLocalEdits && onTimelineChange) {
            onTimelineChange(timelineState);
        }
    }, [timelineState, hasLocalEdits, onTimelineChange]);

    // Check for verified status on mount
    useEffect(() => {
        const checkVerifiedStatus = () => {
            const verifiedIcon = document.querySelector('[data-testid="icon-verified"]');
            if (verifiedIcon) {
                setIsVerified(true);
            }
        };

        checkVerifiedStatus();
    }, []);

    const displayUser = userInfo ? {
        display_name: userInfo.name,
        username: userInfo.handle.replace('@', ''),
        avatar: userInfo.avatar
    } : data.user;

    const handleAutoPost = async () => {
        setIsPosting(true);
        try {
            if (draftOnly) {
                // Draft only: fill compose box without submitting
                await tweetPoster.postThread(timelineState, (current, total) => {
                    setProgress({ current, total });
                }, (uploading) => {
                    setIsUploadingMedia(uploading);
                });
            } else {
                // Auto publish: fill and submit
                const result = await tweetPoster.postThreadWithVerify(
                    timelineState.map(t => ({ text: t.text, media: t.media })),
                    (current, total) => { setProgress({ current, total }); }
                );
                if (!result.success) {
                    throw new Error(result.error || 'Failed to publish');
                }
            }
            setTimeout(() => {
                setIsPosting(false);
                setProgress(null);
            }, 2000);
        } catch (e: any) {
            console.error(e);
            if (!e.message?.includes('Compose modal closed')) {
                alert(`Failed to post: ${e.message || 'Unknown error'}`);
            }
            setIsPosting(false);
            setProgress(null);
        }
    };

    const [generatingIndices, setGeneratingIndices] = useState<Record<number, boolean>>({});

    // Helper to convert base64/URL to Blob
    const urlToBlob = async (url: string): Promise<Blob | null> => {
        try {
            if (url.startsWith('data:')) {
                const parts = url.split(',');
                if (parts.length !== 2) return null;
                const mimeMatch = parts[0].match(/data:([^;]+)/);
                const mime = mimeMatch ? mimeMatch[1] : 'image/png';
                const byteString = atob(parts[1]);
                const ab = new ArrayBuffer(byteString.length);
                const ia = new Uint8Array(ab);
                for (let i = 0; i < byteString.length; i++) {
                    ia[i] = byteString.charCodeAt(i);
                }
                return new Blob([ab], { type: mime });
            } else {
                const response = await fetch(url);
                return await response.blob();
            }
        } catch (error) {
            console.error('Failed to convert URL to blob:', error);
            return null;
        }
    };

    const generateImageForTweet = async (index: number) => {
        // Prevent double trigger if already generating for this index
        if (generatingIndices[index]) return;

        setGeneratingIndices(prev => ({ ...prev, [index]: true }));
        const tweet = timelineState[index];

        try {
            const formData = new FormData();
            formData.append('prompt', `Create an engaging visual illustration for this content: ${tweet.text}`);
            formData.append('model', 'nano-banana-pro');

            const response = await authService.fetchWithAuth('http://localhost:8000/api/v1/ai/generate-image', {
                method: 'POST',
                body: formData,
            });

            if (!response.ok) {
                let errorMsg = 'Generation failed';
                try {
                    const errorBody = await response.json();
                    if (errorBody.detail) errorMsg = typeof errorBody.detail === 'string' ? errorBody.detail : JSON.stringify(errorBody.detail);
                } catch { }
                throw new Error(errorMsg);
            }

            const result = await response.json();
            if (result.data && result.data[0]) {
                const newSrc = `data:${result.data[0].mime_type};base64,${result.data[0].b64_json}`;

                setHasLocalEdits(true);
                setTimelineState(prev => {
                    const newState = [...prev];
                    const newTweet = { ...newState[index] };
                    const newMedia = newTweet.media ? [...newTweet.media] : [];

                    newMedia.push({
                        type: 'photo',
                        media_url: newSrc,
                        url: newSrc,
                        isAIGenerated: true,
                    });

                    newTweet.media = newMedia;
                    newState[index] = newTweet;
                    return newState;
                });
            }
        } catch (error: any) {
            console.error(`Failed to generate image for tweet ${index}:`, error);
        } finally {
            setGeneratingIndices(prev => {
                const newState = { ...prev };
                delete newState[index];
                return newState;
            });
        }
    };

    const handleGenerateNewImage = async (index: number) => {
        // Just trigger generation, concurrency is handled by generatingIndices check inside
        await generateImageForTweet(index);
    };

    const handleImageUpdate = (tweetIndex: number, mediaIndex: number, newSrc: string) => {
        setHasLocalEdits(true);
        setTimelineState(prev => {
            const newState = [...prev];
            const newTweet = { ...newState[tweetIndex] };
            const newMedia = [...newTweet.media];

            newMedia[mediaIndex] = {
                ...newMedia[mediaIndex],
                media_url: newSrc
            };

            newTweet.media = newMedia;
            newState[tweetIndex] = newTweet;
            return newState;
        });
    };

    const handleImageDelete = (tweetIndex: number, mediaIndex: number) => {
        setHasLocalEdits(true);
        setTimelineState(prev => {
            const newState = [...prev];
            const newTweet = { ...newState[tweetIndex] };
            const newMedia = [...newTweet.media];

            // Remove the media item at the specified index
            newMedia.splice(mediaIndex, 1);

            newTweet.media = newMedia;
            newState[tweetIndex] = newTweet;
            return newState;
        });
    };

    const handleTextUpdate = (index: number, newText: string) => {
        setHasLocalEdits(true);
        setTimelineState(prev => {
            const newState = [...prev];
            const newTweet = { ...newState[index], text: newText };
            newState[index] = newTweet;
            return newState;
        });
    };

    // --- RENDER ---

    return (
        <div className="flex flex-col gap-0 w-full max-w-full relative">
            {/* Toast */}
            {toastMsg && (
                <div style={{ position: 'fixed', top: '12px', right: '60px', zIndex: 99999, boxShadow: '0 4px 12px rgba(0,0,0,0.15)' }}
                    className="px-4 py-2.5 bg-white text-black text-sm font-medium rounded-full border border-gray-200"
                >
                    {toastMsg}
                </div>
            )}

            {/* Batch Mode Header controls */}



            {timelineState.map((tweet, index) => {
                const isLast = index === timelineState.length - 1;

                return (
                    <div
                        key={index}
                        className="flex gap-3 relative group transition-colors duration-200 px-4"
                    >

                        {/* Left Sidebar (Avatar + Line) */}
                        <div className="flex flex-col items-center flex-shrink-0 w-10 relative">
                            {/* The connecting line */}
                            {!isLast && (
                                <div
                                    className="absolute top-12 bottom-2 w-[2px] bg-[var(--border-color)]"
                                    style={{ left: '50%', transform: 'translateX(-50%)' }}
                                />
                            )}

                            <img
                                src={displayUser.avatar}
                                alt={displayUser.display_name}
                                className="w-10 h-10 rounded-full border border-[var(--border-color)] bg-[var(--bg-secondary)] object-cover z-10 relative"
                            />
                        </div>

                        {/* Content Area */}
                        <div className={`flex-1 min-w-0 pb-6 ${!isLast ? '' : ''}`}>
                            {/* Header */}
                            <div className="flex items-center justify-between mb-0.5">
                                <div className="flex items-center gap-1 min-w-0 overflow-hidden">
                                    <span className="font-bold text-[var(--text-primary)] text-sm truncate flex items-center gap-1">
                                        {displayUser.display_name}
                                        {isVerified && (
                                            <svg viewBox="0 0 22 22" aria-label="Verified account" role="img" className="w-[18px] h-[18px] text-[#1d9bf0] fill-current">
                                                <g>
                                                    <path d="M20.396 11c-.018-.646-.215-1.275-.57-1.816-.354-.54-.852-.972-1.438-1.246.223-.607.27-1.264.14-1.897-.131-.634-.437-1.218-.882-1.687-.47-.445-1.053-.75-1.687-.882-.633-.13-1.29-.083-1.897.14-.273-.587-.704-1.086-1.245-1.44S11.647 1.62 11 1.604c-.646.017-1.273.213-1.813.568s-.969.97-1.245 1.44c-.606-.223-1.264-.27-1.897-.14-.634.13-1.218.437-1.687.882-.445.469-.751 1.053-.882 1.687-.13.633-.083 1.29.14 1.897-.586.274-1.084.705-1.439 1.246-.354.54-.55 1.17-.569 1.816.017.647.215 1.276.569 1.817.355.54.853.971 1.439 1.245-.223.606-.27 1.263-.14 1.897.131.634.437 1.218.882 1.687.47.445 1.053.75 1.687.882.633.13 1.29.083 1.897-.14.276.587.705 1.086 1.245 1.44.54.354 1.167.55 1.813.568.647-.018 1.275-.214 1.816-.569.54-.354.972-.853 1.245-1.44.606.223 1.264.27 1.897.14.634-.13 1.218-.437 1.687-.882.445-.469.75-1.053.882-1.687.13-.633.083-1.29-.14-1.897.587-.274 1.087-.705 1.438-1.245.355-.54.552-1.17.57-1.817zM9.662 14.85l-3.429-3.428 1.293-1.302 2.072 2.072 4.4-4.794 1.347 1.246z"></path>
                                                </g>
                                            </svg>
                                        )}
                                    </span>
                                    <span className="text-[var(--text-secondary)] text-sm truncate">
                                        @{displayUser.username}
                                    </span>
                                </div>

                                {/* Generate Image Button (Visible on Hover, hidden when 4 images already) */}
                                {(!tweet.media || tweet.media.filter(m => m.type === 'photo').length < 4) && (
                                <button
                                    onClick={() => handleGenerateNewImage(index)}
                                    disabled={!!generatingIndices[index]}
                                    className={`flex items-center gap-1.5 px-2 py-1 rounded-full text-xs font-medium flex-shrink-0 text-[var(--text-secondary)] hover:text-[var(--text-primary)] hover:bg-[var(--hover-bg)] ${generatingIndices[index] ? 'invisible pointer-events-none' : 'transition-all opacity-0 group-hover:opacity-100'}`}
                                    title="Generate Image"
                                >
                                    <Sparkles size={14} />
                                    <span>Generate Image</span>
                                </button>
                                )}
                            </div>

                            {/* Text Content - Editable */}
                            {/* Text Content - Editable */}
                            {/* Text Content - Editable */}
                            <TweetContentEditor
                                value={tweet.text}
                                onChange={(newValue) => handleTextUpdate(index, newValue)}
                                className="text-[var(--text-primary)] text-[15px] leading-[20px] mb-3 w-full bg-transparent p-0 font-normal block"
                            />

                            {/* Image Generation Skeleton */}
                            {generatingIndices[index] && (
                                <div className="w-full aspect-square max-h-[300px] mb-3 rounded-xl overflow-hidden border border-[var(--border-color)]">
                                    <div className="skeleton-shimmer w-full h-full"></div>
                                </div>
                            )}

                            {/* Media */}
                            {tweet.media && tweet.media.length > 0 && (
                                <div className={`grid gap-0.5 mb-3 rounded-xl overflow-hidden border border-[var(--border-color)] ${tweet.media.length === 1 ? 'grid-cols-1' : 'grid-cols-2'
                                    }`}>
                                    {tweet.media.map((media, mIndex) => (
                                        <div key={mIndex} className="relative w-full h-full">
                                            {media.type === 'photo' ? (
                                                <EditableImage
                                                    src={media.media_url}
                                                    prompt={tweet.text}
                                                    className={`w-full h-full bg-[var(--bg-secondary)] object-cover ${tweet.media.length === 1 ? 'max-h-[350px] w-auto object-contain' : 'aspect-square'
                                                        }`}
                                                    onImageUpdate={(newSrc) => handleImageUpdate(index, mIndex, newSrc)}
                                                    onDelete={() => handleImageDelete(index, mIndex)}
                                                    isAIGenerated={media.isAIGenerated}
                                                    hasOriginal={!media.isAIGenerated}
                                                    onPreview={(proxiedSrc) => setPreviewImageUrl(proxiedSrc)}
                                                />
                                            ) : (
                                                <div className="w-full h-full bg-black flex items-center justify-center">
                                                    <TimelineVideo
                                                        src={media.video_url || media.media_url || media.url}
                                                        poster={media.thumbnail || media.thumbnail_url}
                                                        className={`w-full h-full ${tweet.media.length === 1 ? 'max-h-[350px]' : 'aspect-square'}`}
                                                    />
                                                </div>
                                            )}
                                        </div>
                                    ))}
                                </div>
                            )}
                        </div>
                    </div>
                );
            })}


            <div className="mt-2 flex gap-3 w-full px-4">
                <div className="flex flex-col items-center flex-shrink-0 w-10 relative"></div>
                <div className="flex-1 min-w-0 flex items-center justify-between mt-1">
                    {/* Draft Only Toggle Switch - Left aligned */}
                    <div
                        className="flex items-center gap-2 cursor-pointer group"
                        onClick={(e) => {
                            e.stopPropagation();
                            setDraftOnly(!draftOnly);
                        }}
                        title={draftOnly ? "Preview only, won't publish" : "Will publish directly"}
                    >
                        <span className="text-[11px] text-[var(--text-secondary)] font-medium group-hover:text-[var(--text-primary)] transition-colors">
                            Draft only
                        </span>
                        <div
                            className={`relative w-9 h-5 rounded-full transition-colors ${draftOnly ? 'bg-[#1d9bf0]' : 'bg-gray-300 dark:bg-gray-600'} shadow-sm`}
                        >
                            <div className={`absolute top-[2px] w-4 h-4 bg-white rounded-full shadow-sm transition-all duration-200 ${draftOnly ? 'left-[18px]' : 'left-[2px]'}`} />
                        </div>
                    </div>

                    {/* Right side buttons */}
                    <div className="flex items-center gap-2">
                        {/* Scheduled time indicator - only show future schedules */}
                        {scheduledDate && scheduledDate.getTime() > Date.now() ? (
                            <button
                                onClick={() => setShowSchedulePicker(true)}
                                className="flex items-center gap-1.5 px-2.5 py-1 rounded-full bg-blue-50 dark:bg-blue-900/20 text-[#1d9bf0] text-xs font-medium cursor-pointer hover:bg-blue-100 dark:hover:bg-blue-900/30 transition-colors"
                            >
                                <Calendar size={13} />
                                <span>
                                    {scheduledDate.toLocaleDateString(undefined, { month: 'short', day: 'numeric' })}
                                    {' '}
                                    {scheduledDate.toLocaleTimeString(undefined, { hour: '2-digit', minute: '2-digit', hour12: false })}
                                </span>
                            </button>
                        ) : (
                            <button
                                onClick={() => setShowSchedulePicker(true)}
                                className="p-2 rounded-full transition-colors cursor-pointer text-[var(--text-secondary)] hover:bg-[var(--hover-bg)] hover:text-[var(--text-primary)]"
                                title={t.schedule?.title || "设置定时发布"}
                            >
                                <Calendar size={18} />
                            </button>
                        )}

                        <button
                            onClick={handleAutoPost}
                            disabled={isPosting}
                            className={`px-6 h-8 rounded-full font-bold text-sm transition-colors duration-200 flex items-center justify-center gap-2 shadow-sm active:scale-[0.98] ${isPosting
                                ? 'bg-[var(--bg-secondary)] text-[var(--text-secondary)] cursor-not-allowed'
                                : isDark
                                    ? 'bg-[#eff3f4] text-[#0f1419] hover:opacity-90 cursor-pointer'
                                    : 'bg-[#0f1419] text-white hover:opacity-90 cursor-pointer'
                                }`}
                        >
                            <span className="relative flex items-center justify-center">
                                {isPosting && (
                                    <span className="loading loading-spinner loading-xs mr-2"></span>
                                )}
                                <span>
                                    {isPosting
                                        ? (t.article?.publishing || '发布中...')
                                        : (scheduledDate && scheduledDate.getTime() > Date.now())
                                            ? (t.schedule?.scheduledPublish || 'Schedule')
                                            : (t.article?.publish || '发布')
                                    }
                                </span>
                            </span>
                        </button>
                    </div>
                </div>
            </div>

            {/* Image Preview Modal */}
            {
                previewImageUrl && createPortal(
                    <div
                        style={{
                            position: 'fixed',
                            top: 0,
                            left: 0,
                            width: '100vw',
                            height: '100vh',
                            backgroundColor: 'rgba(0, 0, 0, 0.9)',
                            display: 'flex',
                            alignItems: 'center',
                            justifyContent: 'center',
                            zIndex: 2147483647,
                            backdropFilter: 'blur(5px)',
                            opacity: 1,
                            transition: 'opacity 0.2s ease-in-out'
                        }}
                        onClick={() => setPreviewImageUrl(null)}
                    >
                        <button
                            onClick={() => setPreviewImageUrl(null)}
                            style={{
                                position: 'absolute',
                                top: '20px',
                                right: '20px',
                                padding: '10px',
                                borderRadius: '9999px',
                                backgroundColor: 'rgba(255, 255, 255, 0.1)',
                                color: 'white',
                                border: 'none',
                                cursor: 'pointer',
                                display: 'flex',
                                alignItems: 'center',
                                justifyContent: 'center',
                                transition: 'background-color 0.2s'
                            }}
                            onMouseEnter={(e) => (e.currentTarget.style.backgroundColor = 'rgba(255, 255, 255, 0.2)')}
                            onMouseLeave={(e) => (e.currentTarget.style.backgroundColor = 'rgba(255, 255, 255, 0.1)')}
                        >
                            <X size={24} />
                        </button>
                        <img
                            src={previewImageUrl}
                            alt="Preview"
                            style={{
                                maxWidth: '90vw',
                                maxHeight: '90vh',
                                objectFit: 'contain',
                                borderRadius: '12px',
                                boxShadow: '0 25px 50px -12px rgba(0, 0, 0, 0.25)',
                                transform: 'scale(1)',
                                transition: 'transform 0.2s'
                            }}
                            onClick={(e) => e.stopPropagation()}
                        />
                    </div>,
                    document.body
                )
            }

            {/* Media Uploading Notification */}
            <NotificationToast message={t.chat.addingMedia} isVisible={isUploadingMedia} />

            {/* Schedule Picker Modal */}
            {showSchedulePicker && (
                <div
                    className="flex items-center justify-center p-4"
                    style={{
                        position: 'fixed',
                        top: 0,
                        right: 0,
                        width: '486px',
                        height: '100vh',
                        zIndex: 9999,
                        pointerEvents: 'auto',
                        backgroundColor: 'rgba(128, 128, 128, 0.25)',
                    }}
                    onClick={(e) => {
                        if (e.target === e.currentTarget) {
                            setShowSchedulePicker(false);
                        }
                    }}
                >
                    <div
                        style={{
                            backgroundColor: 'var(--bg-primary)',
                            borderRadius: '16px',
                            width: '320px',
                            maxHeight: '80vh',
                            overflow: 'hidden',
                            boxShadow: '0 25px 50px -12px rgba(0, 0, 0, 0.25)'
                        }}
                        onClick={(e) => e.stopPropagation()}
                    >
                        {/* Header */}
                        <div style={{
                            padding: '16px',
                            borderBottom: '1px solid var(--border-color, #eee)',
                            display: 'flex',
                            alignItems: 'center',
                            justifyContent: 'space-between'
                        }}>
                            <span style={{ fontSize: '17px', fontWeight: 700, color: 'var(--text-primary)' }}>
                                {t.schedule?.title || '定时发布'}
                            </span>
                            <button
                                onClick={() => setShowSchedulePicker(false)}
                                style={{
                                    background: 'none',
                                    border: 'none',
                                    padding: '8px',
                                    cursor: 'pointer',
                                    borderRadius: '50%',
                                    display: 'flex',
                                    alignItems: 'center',
                                    justifyContent: 'center'
                                }}
                            >
                                <X size={20} className="text-[var(--text-primary)]" />
                            </button>
                        </div>

                        {/* Calendar */}
                        <div style={{ padding: '16px' }}>
                            {/* Month Navigation */}
                            <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '12px' }}>
                                <button
                                    onClick={() => setScheduleMonth(new Date(scheduleMonth.getFullYear(), scheduleMonth.getMonth() - 1, 1))}
                                    style={{ background: 'none', border: 'none', padding: '8px', cursor: 'pointer', borderRadius: '50%' }}
                                >
                                    <ChevronLeft size={20} className="text-[var(--text-primary)]" />
                                </button>
                                <span style={{ fontSize: '15px', fontWeight: 600, color: 'var(--text-primary)' }}>
                                    {language === 'en'
                                        ? `${['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'][scheduleMonth.getMonth()]} ${scheduleMonth.getFullYear()}`
                                        : `${scheduleMonth.getFullYear()}年 ${scheduleMonth.getMonth() + 1}月`
                                    }
                                </span>
                                <button
                                    onClick={() => setScheduleMonth(new Date(scheduleMonth.getFullYear(), scheduleMonth.getMonth() + 1, 1))}
                                    style={{ background: 'none', border: 'none', padding: '8px', cursor: 'pointer', borderRadius: '50%' }}
                                >
                                    <ChevronRight size={20} className="text-[var(--text-primary)]" />
                                </button>
                            </div>

                            {/* Week Days */}
                            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(7, 1fr)', gap: '2px', marginBottom: '8px' }}>
                                {(language === 'en' ? ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'] : ['日', '一', '二', '三', '四', '五', '六']).map((d, i) => (
                                    <div key={d} style={{ textAlign: 'center', fontSize: '12px', color: i === 0 || i === 6 ? '#f4212e' : 'var(--text-secondary)', padding: '4px' }}>
                                        {d}
                                    </div>
                                ))}
                            </div>

                            {/* Calendar Days */}
                            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(7, 1fr)', gap: '2px' }}>
                                {(() => {
                                    const year = scheduleMonth.getFullYear();
                                    const month = scheduleMonth.getMonth();
                                    const firstDay = new Date(year, month, 1).getDay();
                                    const daysInMonth = new Date(year, month + 1, 0).getDate();
                                    const today = new Date();
                                    const days: (number | null)[] = [];

                                    for (let i = 0; i < firstDay; i++) days.push(null);
                                    for (let d = 1; d <= daysInMonth; d++) days.push(d);

                                    return days.map((day, idx) => {
                                        const isToday = day && day === today.getDate() && month === today.getMonth() && year === today.getFullYear();
                                        const isSelected = scheduledDate && day === scheduledDate.getDate() && month === scheduledDate.getMonth() && year === scheduledDate.getFullYear();
                                        const isPast = day && new Date(year, month, day) < new Date(today.getFullYear(), today.getMonth(), today.getDate());

                                        return (
                                            <div
                                                key={idx}
                                                onClick={() => {
                                                    if (day && !isPast) {
                                                        setScheduledDate(new Date(year, month, day));
                                                    }
                                                }}
                                                style={{
                                                    aspectRatio: '1',
                                                    display: 'flex',
                                                    alignItems: 'center',
                                                    justifyContent: 'center',
                                                    fontSize: '14px',
                                                    borderRadius: '50%',
                                                    cursor: day && !isPast ? 'pointer' : 'default',
                                                    backgroundColor: isSelected ? 'rgb(15, 20, 25)' : isToday ? 'rgba(15, 20, 25, 0.1)' : 'transparent',
                                                    color: isSelected ? '#fff' : isPast ? 'var(--text-secondary)' : 'var(--text-primary)',
                                                    opacity: isPast ? 0.5 : 1,
                                                    fontWeight: isToday || isSelected ? 700 : 400
                                                }}
                                            >
                                                {day}
                                            </div>
                                        );
                                    });
                                })()}
                            </div>

                            {/* Time Selection */}
                            <div style={{ marginTop: '16px', display: 'flex', alignItems: 'center', gap: '12px' }}>
                                <span style={{ fontSize: '14px', color: 'var(--text-secondary)' }}>{t.schedule?.time || 'Time'}</span>
                                <div style={{ display: 'flex', alignItems: 'center', gap: '4px', padding: '8px 12px', border: '1px solid var(--border-color)', borderRadius: '8px' }}>
                                    <select
                                        value={scheduleHour}
                                        onChange={(e) => setScheduleHour(e.target.value)}
                                        style={{ fontSize: '16px', fontWeight: 600, border: 'none', background: 'transparent', color: 'var(--text-primary)', cursor: 'pointer', outline: 'none' }}
                                    >
                                        {Array.from({ length: 24 }, (_, i) => i.toString().padStart(2, '0')).map(h => (
                                            <option key={h} value={h}>{h}</option>
                                        ))}
                                    </select>
                                    <span style={{ fontSize: '16px', fontWeight: 600, color: 'var(--text-primary)' }}>:</span>
                                    <select
                                        value={scheduleMinute}
                                        onChange={(e) => setScheduleMinute(e.target.value)}
                                        style={{ fontSize: '16px', fontWeight: 600, border: 'none', background: 'transparent', color: 'var(--text-primary)', cursor: 'pointer', outline: 'none' }}
                                    >
                                        {Array.from({ length: 12 }, (_, i) => (i * 5).toString().padStart(2, '0')).map(m => (
                                            <option key={m} value={m}>{m}</option>
                                        ))}
                                    </select>
                                </div>
                                <span style={{ fontSize: '12px', color: 'var(--text-tertiary)' }}>
                                    {Intl.DateTimeFormat().resolvedOptions().timeZone}
                                </span>
                            </div>
                        </div>

                        {/* Footer Buttons */}
                        <div style={{ padding: '16px', borderTop: '1px solid var(--border-color, #eee)', display: 'flex', gap: '12px' }}>
                            <button
                                onClick={() => {
                                    setScheduledDate(null);
                                    setShowSchedulePicker(false);
                                    // Unschedule from backend
                                    if (draftId) {
                                        import('../../services/draftService').then(({ draftService }) => {
                                            draftService.unscheduleDraft(draftId).then(() => {
                                                chrome.runtime.sendMessage({ type: 'DRAFT_ALARM_REMOVE', draftId });
                                            }).catch(err => console.error('[RewrittenTimeline] Failed to unschedule:', err));
                                        });
                                    }
                                }}
                                style={{
                                    flex: 1,
                                    padding: '10px',
                                    fontSize: '14px',
                                    fontWeight: 600,
                                    border: '1px solid var(--border-color)',
                                    borderRadius: '9999px',
                                    background: 'transparent',
                                    color: 'var(--text-primary)',
                                    cursor: 'pointer'
                                }}
                            >
                                {t.schedule?.clear || '清除'}
                            </button>
                            <button
                                onClick={() => {
                                    // Default to today if no date selected
                                    const baseDate = scheduledDate || new Date();
                                    const newDate = new Date(baseDate);
                                    newDate.setHours(parseInt(scheduleHour), parseInt(scheduleMinute), 0, 0);

                                    // Block past times
                                    if (newDate.getTime() <= Date.now()) {
                                        showToast(language === 'zh' ? '请选择未来的时间' : 'Please select a future time');
                                        return;
                                    }

                                    setScheduledDate(newDate);
                                    setShowSchedulePicker(false);
                                    // Save to backend and create alarm
                                    if (draftId) {
                                        import('../../services/draftService').then(({ draftService }) => {
                                            draftService.scheduleDraft(draftId, newDate.toISOString()).then(() => {
                                                chrome.runtime.sendMessage({ type: 'DRAFT_ALARM_SYNC', draftId });
                                                console.log('[RewrittenTimeline] Draft scheduled:', draftId, newDate.toISOString());
                                            }).catch(err => console.error('[RewrittenTimeline] Failed to schedule:', err));
                                        });
                                    }
                                }}
                                style={{
                                    flex: 1,
                                    padding: '10px',
                                    fontSize: '14px',
                                    fontWeight: 700,
                                    border: 'none',
                                    borderRadius: '9999px',
                                    backgroundColor: 'rgb(15, 20, 25)',
                                    color: '#fff',
                                    cursor: 'pointer'
                                }}
                            >
                                {t.schedule?.confirm || '确认'}
                            </button>
                        </div>
                    </div>
                </div>
            )}

        </div >
    );
};
