import React, { useState, useEffect } from 'react';
import { Sparkles, Trash2, Undo } from 'lucide-react';
import { authService } from '../services/authService';
import { useTheme } from './ThemeContext';
import { handleImageDragStart } from '../utils/mediaUtils';

export interface EditableImageProps {
    src: string;
    prompt: string;
    onImageUpdate: (newSrc: string) => void;
    onDelete?: () => void;
    className?: string;
    isAIGenerated?: boolean; // Whether this image was generated by AI (from external source)
    hasOriginal?: boolean; // Whether there's an original image to revert to
    onPreview?: (proxiedSrc: string) => void;
}

export const EditableImage: React.FC<EditableImageProps> = ({ src, prompt, onImageUpdate, onDelete, className, isAIGenerated = false, hasOriginal = true, onPreview }) => {
    const [visualSrc, setVisualSrc] = useState(src);
    const [previousSrc, setPreviousSrc] = useState<string | null>(null); // Track previous image for revert
    const [isLoading, setIsLoading] = useState(false);
    const [hasGenerated, setHasGenerated] = useState(isAIGenerated);

    // Sync hasGenerated with isAIGenerated prop when it changes
    useEffect(() => {
        setHasGenerated(isAIGenerated);
    }, [isAIGenerated]);

    // Update visualSrc if prop src changes (unless we are currently editing/loading)
    useEffect(() => {
        setVisualSrc(src);
    }, [src]);

    // Proxy fallback: if image fails to load, try fetching via background (bypass CORS/mixed-content)
    const [triedProxy, setTriedProxy] = useState(false);
    useEffect(() => {
        setTriedProxy(false);
    }, [src]);

    const handleImgError = () => {
        if (!triedProxy && chrome?.runtime?.sendMessage) {
            setTriedProxy(true);
            chrome.runtime.sendMessage({ type: 'FETCH_BLOB', url: src }, (response: any) => {
                if (response?.success && response?.data) {
                    setVisualSrc(response.data);
                }
            });
        }
    };

    // Can revert if: has original image OR has generated within this component (previousSrc exists)
    const canRevert = hasOriginal || previousSrc !== null;

    // Get theme from context
    const { theme } = useTheme();

    // Static button styles for image overlay (always distinct from image)
    const buttonClass = "p-2 rounded-full backdrop-blur-md shadow-sm transition-all bg-black/60 text-white hover:bg-black/80 cursor-pointer";
    const deleteButtonClass = "p-2 rounded-full backdrop-blur-md shadow-sm transition-all bg-black/60 text-white hover:bg-black/80 cursor-pointer";

    const handleGenerate = async (e: React.MouseEvent, isRegenerate: boolean = false) => {
        e.stopPropagation();
        setIsLoading(true);

        try {
            const formData = new FormData();

            // Always use the tweet content as the base prompt for consistency
            const imagePrompt = `Create an engaging visual illustration for this content: ${prompt}`;

            formData.append('prompt', imagePrompt);
            formData.append('model', 'nano-banana-pro');

            // If regenerating, use current image as init image
            if (isRegenerate && visualSrc) {
                try {
                    const blob = await fetch(visualSrc).then(r => r.blob());
                    formData.append('image', blob, 'init_image.png');
                } catch (err) {
                    console.warn("Failed to attach init image for regeneration", err);
                }
            }

            const response = await authService.fetchWithAuth('http://localhost:8000/api/v1/ai/generate-image', {
                method: 'POST',
                body: formData,
            });

            if (!response.ok) {
                let errorMsg = 'Generation failed';
                try {
                    const errorBody = await response.json();
                    if (errorBody.detail) {
                        errorMsg = typeof errorBody.detail === 'string' ? errorBody.detail : JSON.stringify(errorBody.detail);
                    }
                } catch { }
                throw new Error(errorMsg);
            }

            const result = await response.json();
            if (result.data && result.data[0]) {
                const newSrc = `data:${result.data[0].mime_type};base64,${result.data[0].b64_json}`;
                setPreviousSrc(visualSrc); // Save current image before updating
                setVisualSrc(newSrc);
                setHasGenerated(true);
                onImageUpdate(newSrc);
            }
        } catch (error: any) {
            console.error('Failed to generate image:', error);
            alert(error.message || 'Failed to generate image');
        } finally {
            setIsLoading(false);
        }
    };

    const handleRevert = (e: React.MouseEvent) => {
        e.stopPropagation();
        if (previousSrc) {
            // Revert to previous generated image
            setVisualSrc(previousSrc);
            setPreviousSrc(null);
            onImageUpdate(previousSrc);
        }
    };

    return (
        <div className="relative group w-full h-full">
            {/* Always render image to maintain layout - hide when loading but keep space */}
            <img
                src={visualSrc}
                alt="Tweet media"
                draggable={true}
                onDragStart={(e) => handleImageDragStart(e, visualSrc)}
                className={`${className} transition-opacity duration-200 ${isLoading ? 'opacity-0' : 'opacity-100'} ${onPreview ? 'cursor-pointer hover:opacity-95' : ''}`}
                onClick={(e) => {
                    if (onPreview) {
                        e.stopPropagation();
                        onPreview(visualSrc);
                    }
                }}
                onError={handleImgError}
            />

            {/* Skeleton Overlay */}
            {isLoading && (
                <div className="absolute inset-0 z-10 w-full h-full rounded-xl overflow-hidden pointer-events-none">
                    <div className="skeleton-shimmer w-full h-full"></div>
                </div>
            )}

            {/* Overlay Buttons */}
            <div className="absolute top-2 right-2 flex gap-2 z-20 transition-opacity duration-200 opacity-0 group-hover:opacity-100">
                {!hasGenerated && !isLoading && (
                    <>
                        {onDelete && (
                            <button
                                onClick={(e) => {
                                    e.stopPropagation();
                                    onDelete();
                                }}
                                className={deleteButtonClass}
                                title="Remove image"
                            >
                                <Trash2 size={16} strokeWidth={2.5} />
                            </button>
                        )}
                        <button
                            onClick={(e) => handleGenerate(e, false)}
                            className={buttonClass}
                            title="Generate with AI"
                        >
                            <Sparkles size={16} strokeWidth={2.5} />
                        </button>
                    </>
                )}

                {hasGenerated && !isLoading && (
                    <>
                        {onDelete && (
                            <button
                                onClick={(e) => {
                                    e.stopPropagation();
                                    onDelete();
                                }}
                                className={deleteButtonClass}
                                title="Remove image"
                            >
                                <Trash2 size={16} strokeWidth={2.5} />
                            </button>
                        )}
                        {canRevert && (
                            <button
                                onClick={handleRevert}
                                className={buttonClass}
                                title="Revert to previous"
                            >
                                <Undo size={16} strokeWidth={2.5} />
                            </button>
                        )}
                        <button
                            onClick={(e) => handleGenerate(e, true)}
                            className={buttonClass}
                            title="Regenerate"
                        >
                            <Sparkles size={16} strokeWidth={2.5} />
                        </button>
                    </>
                )}
            </div>
        </div>
    );
};
