name = "bnbot"
main = ".open-next/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[vars]
NEXT_PUBLIC_REST_API_ENDPOINT = "https://api.bnbot.ai"
NEXT_PUBLIC_GOOGLE_CLIENT_ID = "968791771361-on89kib06tl0kucdoo0s7jiop3tftp16.apps.googleusercontent.com"

[assets]
directory = ".open-next/assets"
